Vagrant.configure("2") do |config|
  # Optional: manage /etc/hosts on host and guests
  if Vagrant.has_plugin?("vagrant-hostmanager")
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.include_offline = true
  end

  # Nagios server
  config.vm.define "mon01" do |mon|
    mon.vm.hostname = "mon01"
    mon.vm.box = "generic/rocky9"
    mon.vm.network "private_network", ip: "192.168.56.16"
    mon.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    mon.vm.provision "shell", path: "scripts/nagios_provision.sh"
  end
end
